title: Evolutionary and Cross-Cultural Psychology
logo_img: /assets/img/icons/soheilshapouri.svg
favicon: /assets/favicon.ico
description: When I am not teaching statistics and research methods, I explore how natural disasters, infectious diseases, and other environmental threats shape national cultures, affect social behaviors, and impact emotional experiences through interdisciplinary research.  
global_tags: 
copyright:  

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
