title: Evolution of Fear and Disgust
logo_img: /assets/img/icons/golasblog_logo.svg
favicon: /assets/favicon.ico
description: How do natural disasters, epidemics, and other environmental threats affect national cultures, social behavior, and emotional experiences?.
global_tags: 
copyright: Soheil Shapouri 

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
