title: Evolution of Fear and Disgust
logo_img: /assets/img/icons/soheilshapouri.svg
favicon: /assets/favicon.ico
description: How do natural disasters, infectious diseases, and other environmental threats shape national cultures, affect social behaviors, and impact emotional experiences? Using concepts and methods from social psychology, risk science, and machine learning, I aim to answer this question through multidiciplinary research.
global_tags: 
copyright:  

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
